apiVersion: v1
kind: PersistentVolume

metadata:
  name: azurefile-pv
  namespace: default
  labels:
    type: azurefile

spec:
  azureFile:
    secretName: azure-secret
    shareName: pod-share
  accessModes:
    - ReadWriteMany 
  capacity:
    storage: 10Gi

  persistentVolumeReclaimPolicy: Retain

  storageClassName: azurefile-sc

  # csi:
  #   driver: file.csi.azure.com

  #   volumeHandle: azurefile-volume

  #   volumeAttributes:
  #     shareName: myfileshare

  #   nodeStageSecretRef:
  #     name: azure-secret
  #     namespace: default 