apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  azurestorageaccountname: podstorageink8s 
  azurestorageaccountkey: jEuSEIeCLF6UV7EV9V1bpO3msmV3TeA5zIVm6056OFkWhfz2YVV9SM3cXUhj4kdLn6IYoqQUVSlr+AStMUhJHA==